

package com.apitable.shared.grpc;

import com.apitable.integration.grpc.BasicResult;
import com.apitable.integration.grpc.DocumentAssetStatisticResult;
import com.apitable.integration.grpc.DocumentAssetStatisticRo;
import com.apitable.integration.grpc.NodeCopyRo;
import com.apitable.integration.grpc.NodeDeleteRo;

/**
 * grpc client interface.
 */
public interface IGrpcClientService {
    /**
     * The changesets generated by the replication nodes are generated through the middle layer and notified to the long chain room.
     *
     * @param ro request the parameters of the middle layer
     * @return BasicResult
     */
    BasicResult nodeCopyChangeset(NodeCopyRo ro);

    /**
     * Generate changesets generated by deleting nodes through the middle layer, and notify the long chain room.
     *
     * @param ro request the parameters of the middle layer
     * @return BasicResult
     */
    BasicResult nodeDeleteChangeset(NodeDeleteRo ro);

    /**
     * Document asset statistic request.
     *
     * @param ro DocumentAssetStatisticRo
     * @return DocumentAssetStatisticResult
     * @author Chambers
     */
    DocumentAssetStatisticResult documentAssetStatistic(DocumentAssetStatisticRo ro);
}
